### ISSUE TITLE
Release a Beta of the Twig-based Standard Edition

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/edition-php-twig-development#10]
The Twig-based Development Edition is meant to be an unstable platform for developing and testing changes to Twig-related components. With more interest in Twig support in Pattern Lab it'd be good to push out a beta of the Twig-based Standard Edition. Along with creating the beta I need to address issues that have come up regarding workflow and StarterKits. A quick task list:

* [x] update the Watch command to support watching Composer-installed StarterKits for easier StarterKit development
* [x] update the Fetch command to support the download & install of StarterKits from GitHub to avoid dependency issues. still utilize a `composer.json` to determine install locations via `InstallerUtil`.
* [x] add Init command to initialize a project and prompt for StarterKit install if one _wasn't_ installed based on a dependency in `composer.json`
* [x] add merge/replace option to install of StarterKits (_affects Fetch and InstallerUtil_)
* [x] add support for macros to the Twig PatternEngine per issue #5 
* [x] add PatternEngine-specific configs per #11 (_dump, date support_)
* [ ] ~~add events to PatternEngines so they can be extended via plugins rather than baking everything in directly~~ (_probably going to have to deal with baking things in. lots of moving parts here_)
* [x] make the supported extension for a PatternEngine an array and add method to add to to it per issue pattern-lab/patternlab-php#211 (_added a method to update PatternData rules, that was the proper solution in retrospect_)
* [x] make sure config directives for arrays merge rather than replace
* [ ] ~~make PL unicode friendly by use `mb_*` functions per [phprightway.com](http://www.phptherightway.com/#php_and_utf8)~~ (_not a simple fix. would be good to do at some point_)
* [x] remove "header options" copy from Mustache and Twig StyleguideKits
* [x] create base/thin StarterKits for Mustache and Twig
* [x] make sure the custom styleguide CSS override exists in the StarterKits
* [x] update copy for various components
* [x] add `v0.*` tags to various components to create a true stable beta release
* [x] create a Twig Standard Edition

Nothing listed above is breaking new ground so should be straightforward to accomplish. Expect delivery by the end of the weekend if not sooner.

Extra info:

* [Twig components](https://github.com/pattern-lab/edition-php-twig-development/issues/1)
* discussion on [the parts that make up a Pattern Lab project](https://github.com/pattern-lab/edition-php-thin/issues/1#issuecomment-49741385)
* more in-depth [discussion on Editions and StarterKits](https://github.com/pattern-lab/patternlab-php/issues/273#issuecomment-75471333)

**Comment by dmolsen** [comment]
This is available as the [Standard Edition for Twig](https://github.com/pattern-lab/edition-php-twig-standard).
